version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10
    groups:
      nosto:
        patterns:
          - "@nosto/*"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@types/eslint-*"
          - "prettier"
      semantic-release:
        patterns:
          - "@semantic-release/*"
          - "semantic-release"
      testing:
        patterns:
          - "@playwright/test"
          - "@testing-library/*"
          - "vitest"
          - "jsdom"
      typescript:
        patterns:
          - "typescript"
          - "typescript-*"
          - "@types/*"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"
      vite:
        patterns:
          - "vite"
          - "@preact/preset-vite"
          - "rollup-*"
      preact:
        patterns:
          - "preact"
      commitlint:
        patterns:
          - "@commitlint/*"